import { Download } from 'lucide-react';
import { jsPDF } from 'jspdf';
import type { AuditResult } from '../modules/types';

interface PdfDownloadButtonProps {
  results: AuditResult[];
  url: string;
}

export function PdfDownloadButton({ results, url }: PdfDownloadButtonProps) {
  const generatePdf = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    doc.setFontSize(20);
    doc.text('Varabit SEO Audit Report', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition);
    yPosition += 6;
    doc.text(`URL: ${url}`, margin, yPosition);
    yPosition += 15;

    results.forEach((result) => {
      if (yPosition > pageHeight - 40) {
        doc.addPage();
        yPosition = margin;
      }

      doc.setFontSize(14);
      doc.setTextColor(0);
      doc.text(result.module, margin, yPosition);
      yPosition += 8;

      doc.setFontSize(10);
      const statusColor = result.status === 'pass' ? [34, 197, 94] :
                         result.status === 'warning' ? [234, 179, 8] :
                         [239, 68, 68];
      doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
      doc.text(`Status: ${result.status.toUpperCase()}`, margin, yPosition);
      yPosition += 6;

      doc.setTextColor(0);
      doc.text(`Summary: ${result.summary}`, margin, yPosition);
      yPosition += 8;

      if (result.issues.length > 0) {
        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        doc.text('Issues:', margin, yPosition);
        doc.setFont(undefined, 'normal');
        yPosition += 5;

        result.issues.forEach((issue) => {
          const lines = doc.splitTextToSize(`- ${issue}`, maxWidth - 5);
          lines.forEach((line: string) => {
            if (yPosition > pageHeight - 20) {
              doc.addPage();
              yPosition = margin;
            }
            doc.text(line, margin + 5, yPosition);
            yPosition += 5;
          });
        });
        yPosition += 3;
      }

      if (result.suggestions.length > 0) {
        doc.setFont(undefined, 'bold');
        doc.text('Suggestions:', margin, yPosition);
        doc.setFont(undefined, 'normal');
        yPosition += 5;

        result.suggestions.forEach((suggestion) => {
          const lines = doc.splitTextToSize(`- ${suggestion}`, maxWidth - 5);
          lines.forEach((line: string) => {
            if (yPosition > pageHeight - 20) {
              doc.addPage();
              yPosition = margin;
            }
            doc.text(line, margin + 5, yPosition);
            yPosition += 5;
          });
        });
      }

      yPosition += 10;
    });

    if (yPosition > pageHeight - 30) {
      doc.addPage();
      yPosition = margin;
    }

    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Generated by Varabit SEO Audit Tool v1.0.0', margin, pageHeight - 15);
    doc.text('Contact: support@varabit.com | License: GPL v2 or later', margin, pageHeight - 10);

    const fileName = `seo-audit-${new URL(url).hostname}-${Date.now()}.pdf`;
    doc.save(fileName);
  };

  return (
    <button
      onClick={generatePdf}
      className="px-6 py-3 bg-slate-800 text-white font-medium rounded-lg hover:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-slate-500 focus:ring-offset-2 flex items-center gap-2 transition-colors"
    >
      <Download className="w-5 h-5" />
      <span>Download PDF Report</span>
    </button>
  );
}
